<img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png">

# NumPy basics
**Num Py means Numerical Python**<br>
**Why use Numpy??**<br>
**Normal Python List is slow as it is not compact (Can store different types of data)**<br>

**Numpy contain same type of data**<br>
**Numpy is written in C programming hence it is fast**

In [1]:
# pip install numpy
import numpy as np 
l = ['1', '2', '3']
ans = np.array(l)
ans 

array(['1', '2', '3'], dtype='<U1')

In [2]:
ans = np.zeros(10)
ans

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ans = np.ones(5)
ans 

array([1., 1., 1., 1., 1.])

In [4]:
ans = np.zeros((3,3))
ans

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
ans = np.ones((3,4), int)
ans 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
ans = np.zeros(10, int)
ans[0] = "1"
ans 

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# This is an error 
ans = np.zeros(10, int)
ans[0] = "Machine Learning"
ans 

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [16]:
ans = np.zeros(10, int)
ans[:5:1]

array([0, 0, 0, 0, 0])

In [20]:
ans = np.ones((3,3), int)
ans[0, 1:]

array([1, 1])

In [21]:
ans = np.ones((3,3), int)
ans[:, 0]

array([1, 1, 1])

# Terms
**1-D array : Vector**<br>
**2-D array : Matrix**<br>
**3-D array: Tensor**

In [22]:
v = [1,2,3,4]
a = np.diag(v)
a 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
a = np.eye(3,4)
a 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [31]:
ans = np.random.randint(1,10,3)
ans 

array([5, 5, 5])

In [36]:
ans = np.random.random((5,5))
ans 

array([[0.48643969, 0.90608739, 0.61604137, 0.26612495, 0.97990568],
       [0.41517062, 0.310031  , 0.23830135, 0.62175462, 0.37673482],
       [0.55188915, 0.13730904, 0.76803052, 0.65076927, 0.14406641],
       [0.55236564, 0.09074217, 0.83499368, 0.06841997, 0.04420308],
       [0.93015994, 0.59648172, 0.21433984, 0.71864866, 0.65425949]])